---
- name: Install node and npm
  # replace with your host IP address
  hosts: X.X.X.X
  tasks:
    - name: Update apt repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Install nodejs and npm
      apt:
        pkg:
          - nodejs
          - npm


- name: Create new linux user for node app
  # replace with your host IP address
  hosts: X.X.X.X
  tasks:
    - name: Create linux user
      user:
      # replace with your username
        name: "{{linux_name}}"
        comment: Node User
        group: admin


- name: Deploy nodejs app
  # replace with your host IP address
  hosts: X.X.X.X
  become: True
  # replace with your username
  become_user: "{{linux_name}}"
  vars_files:
    project-vars
  tasks:
    - name: Unpack the nodejs file
      unarchive:
        # replace with your folder location
        src: "{{location}}/nodejs-app-{{version}}.tgz"
        # replace with your folder location
        dest: "{{user_home_dir}}"
    - name: Install dependencies
      npm:
        # replace with your folder location
        path: "{{user_home_dir}}/package"
    - name: Start the application
      command:
        # replace with your folder location
        chdir: "{{user_home_dir}}/package/app"
        cmd: node server
      async: 1000
      poll: 0
    - name: Ensure app is running
      shell: ps aux | grep node
      register: app_status
    - debug: msg={{app_status.stdout_lines}}
